#!/bin/bash
if [ $# -lt 1 ]; then
	echo "$(basename "$BASH_SOURCE") [src] [out] [rmk]"
	exit 1
fi
src=$1
out=$2
rmk="/* $3 */"
tool=${tools:-$(dirname "$BASH_SOURCE")/tools}
if [ -z "$out" ]; then
	out="$(dirname $src)/$(basename -s .css $src)-min.css"
fi
echo -n "compress css file $src to $out"
if [ -z "$rmk" ]; then
	java -jar "$tool/yuicompressor.jar" $src --charset utf-8 -o $out
else
	echo "$rmk" > $out
	java -jar "$tool/yuicompressor.jar" $src --charset utf-8 >> $out
fi
echo " - done!"
