#!/bin/bash
if [ $# -lt 1 ]; then
	echo "$(basename "$BASH_SOURCE") [src] [out]"
	exit 1
fi
src=$1
out=$2
tool=${tools:-$(dirname "$BASH_SOURCE")/tools}
if [ -z "$out" ]; then
	out="$(dirname $src)/$(basename -s .html $src)-min.html"
fi
echo -ne "compress html file $src to $out"
java -jar "$tool/htmlcompressor.jar" --remove-surrounding-spaces all --compress-js --js-compressor closure --compress-css -o $out $src
echo " - done!"
