#!/bin/bash
if [ $# -lt 1 ]; then
	echo "$(basename "$BASH_SOURCE") [src] [out] [rmk]"
	exit 1
fi
src=$1
out=$2
rmk="// $3"
tool=${tools:-$(dirname "$BASH_SOURCE")/tools}
if [ -z "$out" ]; then
	out="$(dirname $src)/$(basename -s .css $src)-min.js"
fi
echo -n "compress js file $src to $out"
if [ -z "$rmk" ]; then
	java -jar "$tool/compiler.jar" --js $src --js_output_file $out --compilation_level SIMPLE_OPTIMIZATIONS
else
	echo "$rmk" > $out
	java -jar "$tool/compiler.jar" --js $src --compilation_level SIMPLE_OPTIMIZATIONS >> $out
fi
echo " - done!"
