#!/bin/sh
if [ $# -lt 1 ]; then
	find . -name .DS_Store -o -name "._*" -depth
elif [ "$1" = "clean" ]; then
	find . -name .DS_Store -depth -exec rm {} \;
	echo cleaned
else
	echo "cannot understand $1"
fi
