#!/bin/sh
if [ $# -lt 1 ]; then
    echo "empty input"
    exit 1
fi
dir="$1"
if test -d "$dir"; then
    [ "$p" = "" ] && p=$(dirname "$dir")/
    b=$(basename "$dir")
    f="$p$b.txz"
    if test -f "$ff$x"; then
        if [ "$f" = "on" ]; then
            rm -f "$ff$x"
        else
            echo "$ff$x exists"
            exit 1
        fi
    fi
    echo "tar xz $dir to $f"
    XZ_OPT=-9e tar --exclude='__MACOSX*' --exclude='*.DS_Store' -cvJf "$f" "$dir"
    echo "$f Done!"
    exit
else
    echo "$dir not extis"
    exit 1
fi
